# Use a PV only if this is a test case, not for production!
{{- if .Values.hauler.data.test }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hauler-data-pv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hauler.labels" . | nindent 4 }}
spec:
  {{- if .Values.hauler.data.pvc.storageClass }}
  storageClassName: {{ .Values.hauler.data.pvc.storageClass }}
  {{- else }}
  storageClassName: standard
  {{- end }}
  accessModes:
  - {{ .Values.hauler.data.pvc.accessModes }}
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/
  resources:
    requests:
      storage: {{ .Values.hauler.data.pvc.storageRequest }}
{{- end }}
