{{- if and (or .Values.haulerJobs.remote .Values.haulerJobs.local) (or (and .Values.haulerJobs.local .Values.haulerJobs.local.store) (and .Values.haulerJobs.remote .Values.haulerJobs.remote.artifacts (gt (len .Values.haulerJobs.remote.artifacts) 0)) (and .Values.haulerJobs.remote .Values.haulerJobs.remote.manifests (gt (len .Values.haulerJobs.remote.manifests) 0))  (and .Values.haulerJobs.local .Values.haulerJobs.local.artifacts (gt (len .Values.haulerJobs.local.artifacts) 0)) (and .Values.haulerJobs.local .Values.haulerJobs.local.manifests (gt (len .Values.haulerJobs.local.manifests) 0))  ) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: hauler-loader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hauler.labels" . | nindent 4 }}
    {{- with .Values.hauler.labels -}}
{{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.hauler.annotations -}}
{{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    spec:
      initContainers:
        - name: hauler-fetch
          image: {{ .Values.haulerJobs.image.repository }}:{{ .Values.haulerJobs.image.tag }}
          imagePullPolicy: {{ .Values.haulerJobs.imagePullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.store }}
              cp -r /local-store/* /store/   &&
              chown -R 1001:1001 /store &&
              echo copied {{ .Values.haulerJobs.local.store }} &&
              {{- end }}
              {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.artifacts }}
              {{- range .Values.haulerJobs.local.artifacts }}
              cp -va /tmp/local-artifact-{{ .name }} /artifacts/ &&
              {{- end}}
              {{- end}}
              {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.manifests }}
              {{- range .Values.haulerJobs.local.manifests }}
              cp -va /tmp/local-manifest-{{ .name }} /manifests/ &&
              {{- end}}
              {{- end}}
              {{- if and .Values.haulerJobs.remote .Values.haulerJobs.remote.artifacts }}
              {{- range .Values.haulerJobs.remote.artifacts }}
              curl -o /artifacts/{{ .name }} {{ .path }} &&
              {{- end }}
              {{- end }}
              {{- if and .Values.haulerJobs.remote .Values.haulerJobs.remote.manifests }}
              {{- range .Values.haulerJobs.remote.manifests }}
              curl -o /manifests/{{ .name }} {{ .path }} &&
              {{- end }}
              {{- end }}
              echo hauler fetch completed
          volumeMounts:
            {{- if or (and .Values.haulerJobs.remote .Values.haulerJobs.remote.artifacts (gt (len .Values.haulerJobs.remote.artifacts) 0)) (and .Values.haulerJobs.local .Values.haulerJobs.local.artifacts (gt (len .Values.haulerJobs.local.artifacts) 0)) }}
            - name: artifact-data
              mountPath: /artifacts
            {{- end }}
            {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.artifacts (gt (len .Values.haulerJobs.local.artifacts) 0) }}
            {{- range .Values.haulerJobs.local.artifacts }}
            - name: local-artifact-{{ .name }}
              mountPath: /tmp/local-artifact-{{ .name }}
            {{- end }}
            {{- end }}
            {{- if or (and .Values.haulerJobs.remote .Values.haulerJobs.remote.manifests (gt (len .Values.haulerJobs.remote.manifests) 0)) (and .Values.haulerJobs.local .Values.haulerJobs.local.manifests (gt (len .Values.haulerJobs.local.manifests) 0)) }}
            - name: manifest-data
              mountPath: /manifests
            {{- end }}
            {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.manifests (gt (len .Values.haulerJobs.local.manifests) 0) }}
            {{- range .Values.haulerJobs.local.manifests }}
            - name: local-manifest-{{ .name }}
              mountPath: /tmp/local-manifest-{{ .name }}
            {{- end }}
            {{- end }}
            {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.store }}
            - name: store-data
              mountPath: /local-store
            {{- end }}
            - name: hauler-data
              mountPath: /store
          securityContext:
            runAsUser: 0
      containers:
        - name: hauler-load
          image: {{ .Values.hauler.image.repository }}:{{ .Values.hauler.image.tag }}
          imagePullPolicy: {{ .Values.hauler.imagePullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
            {{- if and .Values.haulerJobs.remote .Values.haulerJobs.remote.artifacts (gt (len .Values.haulerJobs.remote.artifacts) 0) }}
            {{- range .Values.haulerJobs.remote.artifacts }}
              hauler store -s /store load /artifacts/{{ .name }} &&
            {{- end }}
            {{- end }}
            {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.artifacts (gt (len .Values.haulerJobs.local.artifacts) 0) }}
            {{- range .Values.haulerJobs.local.artifacts }}
              hauler store -s /store load /artifacts/{{ .name }} &&
            {{- end }}
            {{- end }}
            {{- if and .Values.haulerJobs.remote .Values.haulerJobs.remote.manifests (gt (len .Values.haulerJobs.remote.manifests) 0) }}
            {{- range .Values.haulerJobs.remote.manifests }}
              hauler store -s /store sync --files /manifests/{{ .name }} &&
            {{- end }}
            {{- end }}
            {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.manifests (gt (len .Values.haulerJobs.local.manifests) 0) }}
            {{- range .Values.haulerJobs.local.manifests }}
              hauler store -s /store sync --files /manifests/{{ .name }} &&
            {{- end }}
            {{- end }}
              echo hauler load completed &&
              ls -lha /store
          volumeMounts:
            {{- if and .Values.haulerJobs.remote .Values.haulerJobs.remote.artifacts (gt (len .Values.haulerJobs.remote.artifacts) 0) }}
            - name: artifact-data
              mountPath: /artifacts
            {{- end }}
            {{- if and .Values.haulerJobs.remote .Values.haulerJobs.remote.manifests (gt (len .Values.haulerJobs.remote.manifests) 0) }}
            - name: manifest-data
              mountPath: /manifests
            {{- end }}
            {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.store }}
            - name: store-data
              mountPath: /local-store
            {{- end }}
            - name: hauler-data
              mountPath: /store
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: OnFailure
      volumes:
        {{- if or (and .Values.haulerJobs.remote .Values.haulerJobs.remote.artifacts (gt (len .Values.haulerJobs.remote.artifacts) 0)) (and .Values.haulerJobs.local .Values.haulerJobs.local.artifacts (gt (len .Values.haulerJobs.local.artifacts) 0)) }}
        - name: artifact-data
          emptyDir:
        {{- end }}
        {{- if (and .Values.haulerJobs.local .Values.haulerJobs.local.artifacts (gt (len .Values.haulerJobs.local.artifacts) 0)) }}
        {{- range .Values.haulerJobs.local.artifacts }}
        - name: local-artifact-{{ .name }}
          hostPath: 
            path: {{ .path }}
        {{- end }}
        {{- end }}
        {{- if or (and .Values.haulerJobs.remote .Values.haulerJobs.remote.manifests (gt (len .Values.haulerJobs.remote.manifests) 0)) (and .Values.haulerJobs.local .Values.haulerJobs.local.manifests (gt (len .Values.haulerJobs.local.manifests) 0)) }}
        - name: manifest-data
          emptyDir:
        {{- end }}
        {{- if (and .Values.haulerJobs.local .Values.haulerJobs.local.manifests (gt (len .Values.haulerJobs.local.manifests) 0)) }}
        {{- range .Values.haulerJobs.local.manifests }}
        - name: local-manifest-{{ .name }}
          hostPath: 
            path: {{ .path }}
        {{- end }}
        {{- end }}
        {{- if and .Values.haulerJobs.local .Values.haulerJobs.local.store }}
        - name: store-data
          hostPath:
            path: {{ .Values.haulerJobs.local.store }}
        {{- end }}
        - name: hauler-data
          persistentVolumeClaim:
            claimName: hauler-data
{{- end }}
