apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: helm-test
  labels:
    app: test
spec:
  containers:
    - name: test-container
      image: hauler/hauler-debug:1.1.1
      command: [ "sleep", "3600" ]