name: Lint, Install, and Test Charts

on: push

jobs:
  test-hauler-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --all

      - name: Setup k3s
        run: curl -sfL https://get.k3s.io | sh - ; mkdir ~/.kube ; sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config ; sudo chown runner ~/.kube/config

      - name: Wait for k3s
        run: |
          while ! kubectl get po -n kube-system -l app.kubernetes.io/name=traefik -ojsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q true
          do
          sleep 1
          done

      - name: Install Test Cases
        run: |
          for testvalue in $(ls charts/hauler/ci/*-values.yaml)
          do
            name=$(basename ${testvalue}| rev | cut -c13- | rev)
            namespace=hauler-${name}
            echo $name - $testvalue
            helm install $name charts/hauler --namespace ${namespace} --values ${testvalue} --create-namespace
          done

      - name: Download & Prep "local" Test Files
        run: |
          mkdir -pv /tmp/tests/store
          echo "Download local-haul.tar.zst"
          curl -o /tmp/tests/local-haul.tar.zst https://raw.githubusercontent.com/hauler-dev/hauler/main/testdata/haul.tar.zst
          echo "Download local-manifest.yaml"
          curl -o /tmp/tests/local-manifest.yaml https://raw.githubusercontent.com/tayterz2/hauler-helm/refs/heads/main/charts/hauler/ci/test-manifest.yaml
          echo "Download hauler binary"
          curl -sfL https://get.hauler.dev | HAULER_VERSION=1.2.0 bash
          echo "Create local store"
          hauler store -s /tmp/tests/store sync --filename charts/hauler/ci/store-manifest.yaml
          echo "Store built in /tmp/tests/store"

      - name: Wait for Installs/Loads
        run: |
          while kubectl get po -A -lapp=hauler-registry -ojsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q "false"
          do
            for testvalue in $(ls charts/hauler/ci/*-values.yaml)
            do
              name=$(basename ${testvalue}| rev | cut -c13- | rev)
              namespace=hauler-${name}
              echo kubectl logs -n $namespace -lbatch.kubernetes.io/job-name=hauler-loader -c hauler-fetch
              kubectl logs -n $namespace -lbatch.kubernetes.io/job-name=hauler-loader -c hauler-fetch || echo still waiting for fetch
              echo kubectl logs -n $namespace -lbatch.kubernetes.io/job-name=hauler-loader -c hauler-load
              kubectl logs -n $namespace -lbatch.kubernetes.io/job-name=hauler-loader -c hauler-load || echo still waiting for load
            done
            echo "waiting for registries to start"
            sleep 1
          done
          while kubectl get po -A -lapp=hauler-fileserver -ojsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q "false"
          do
            echo "waiting for fileservers to start"
            sleep 5
          done
          sleep 10

      - name: Get debug output
        run: |
          kubectl apply -f charts/hauler/ci/test-pod.yaml
          while ! kubectl get po test-pod -ojsonpath='{.status.containerStatuses[0].ready}' | grep true
          do
            sleep 1
          done
          for testvalue in $(ls charts/hauler/ci/*-values.yaml)
          do
            name=$(basename ${testvalue}| rev | cut -c13- | rev)
            namespace=hauler-${name}
            REGISTRY_URL=http://hauler-registry.${namespace}.svc.cluster.local:5000/v2/_catalog
            echo REGISTRY_URL = $REGISTRY_URL
            kubectl exec -q test-pod -- curl -s ${REGISTRY_URL} > /tmp/registry_output.txt
            echo registry output:
            cat /tmp/registry_output.txt
            echo kubectl -n $namespace logs -lapp=hauler-registry
            kubectl -n $namespace logs -lapp=hauler-registry || true
            HTTP_URL=http://hauler-fileserver.${namespace}.svc.cluster.local:8080
            echo HTTP_URL = $HTTP_URL
            kubectl exec -q test-pod -- curl -s ${HTTP_URL} > /tmp/fileserver_output.txt
            echo file output:
            cat /tmp/fileserver_output.txt
            echo kubectl -n $namespace logs -lapp=hauler-fileserver
            kubectl -n $namespace logs -lapp=hauler-fileserver || true
          done
