name: Lint, Install, and Test Charts

on: push

jobs:
  test-hauler-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.16.4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --all

      - name: Setup k3s
        run: curl -sfL https://get.k3s.io | sh - ; mkdir ~/.kube ; sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config ; sudo chown runner ~/.kube/config

      - name: Wait for k3s
        run: |
          while ! kubectl get po -n kube-system -l app.kubernetes.io/name=traefik -ojsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q true
          do
          sleep 1
          done

      - name: Install Test Cases
        run: |
          for testvalue in $(ls charts/hauler/ci/*-values.yaml)
          do
            name=$(basename ${testvalue}| rev | cut -c13- | rev)
            namespace=hauler-${name}
            echo $name - $testvalue
            helm install $name charts/hauler --namespace ${namespace} --values ${testvalue} --create-namespace
          done

      - name: Download & Prep "local" Test Files
        run: |
          mkdir -pv /tmp/tests/store
          echo "Download local-haul.tar.zst"
          curl -o /tmp/tests/local-haul.tar.zst https://raw.githubusercontent.com/hauler-dev/hauler/main/testdata/haul.tar.zst
          echo "Download local-manifest.yaml"
          curl -o /tmp/tests/local-manifest.yaml https://raw.githubusercontent.com/tayterz2/hauler-helm/refs/heads/main/charts/hauler/ci/test-manifest2.yaml
          echo "Download hauler binary"
          curl -sfL https://get.hauler.dev | HAULER_VERSION=1.2.0 bash
          echo "Create local store"
          hauler store -s /tmp/tests/store load --filename /tmp/tests/local-haul.tar.zst
          echo "Store built in /tmp/tests/store"

      - name: Wait for Installs/Loads and Tester Pod
        run: |
          echo -n "waiting for registries to start"
          while kubectl get po -A -lapp=hauler-registry -ojsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q "false"
          do
            #echo -n . ; sleep 5
            kubectl get po -A | grep -v 'Running\|Completed'
            sleep 1
          done
          echo
          echo -n "waiting for fileservers to start"
          while kubectl get po -A -lapp=hauler-fileserver -ojsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -q "false"
          do
            echo -n . ; sleep 1
          done
          echo
          kubectl apply -f charts/hauler/ci/test-pod.yaml
          while ! kubectl get po test-pod -ojsonpath='{.status.containerStatuses[0].ready}' | grep true
          do
            sleep 1
          done

      - name: Gather Test Results and Compare
        run: |
          successes=""
          failures=""
          for testvalue in $(ls charts/hauler/ci/*-values.yaml)
          do
            name=$(basename ${testvalue}| rev | cut -c13- | rev)
            namespace=hauler-${name}
            REGISTRY_URL=http://hauler-registry.${namespace}.svc.cluster.local:5000/v2/_catalog
            kubectl exec -q test-pod -- curl -s ${REGISTRY_URL} > /tmp/${name}-reg-output.txt
            HTTP_URL=http://hauler-fileserver.${namespace}.svc.cluster.local:8080
            kubectl exec -q test-pod -- curl -s ${HTTP_URL} > /tmp/${name}-web-output.txt
            if diff -q charts/hauler/ci/expected/${name}-web-output.txt /tmp/${name}-web-output.txt
            then
              successes="${successes} ${name}-web"
            else
              failures="${failures} ${name}-web"
            fi
            if diff -q charts/hauler/ci/expected/${name}-reg-output.txt /tmp/${name}-reg-output.txt
            then
              successes="${successes} ${name}-reg"
            else
              failures="${failures} ${name}-reg"
            fi
          done
          
          if ! [ -z "$failures" ]
          then
            echo there were failures, investigate these tests: $failures
            exit 1
          else
            echo all tests passed: $successes
          fi
